# Generated by Django 6.0 on 2026-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandstory_craftsmanshipitem_herosection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aging_process',
            field=models.TextField(blank=True, default='Unique patina develops over time'),
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.TextField(blank=True, help_text='Khả năng chứa (VD: 9 card slots)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collab_info',
            field=models.CharField(default='NAMGIA-ATELIER x LUISSIMI', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='craftsmanship',
            field=models.CharField(default='100% Handmade, meticulous hand-stitching', help_text='Nghệ thuật thủ công', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='design_style',
            field=models.CharField(blank=True, help_text='VD: Minimalist, gender-neutral', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='VD: 20 x 10 x 2 cm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_detail',
            field=models.CharField(blank=True, help_text='VD: Italian Pull-up leather', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='Trọng lượng sản phẩm', max_length=100, null=True),
        ),
    ]
