# Generated by Django 6.0 on 2026-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_aging_process_product_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên màu')),
                ('hex_code', models.CharField(help_text='VD: #800020', max_length=7, verbose_name='Mã màu Hex')),
            ],
        ),
    ]
