# Generated by Django 6.0 on 2026-01-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsmanshipitem',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả ngắn về giá trị cốt lõi', null=True),
        ),
    ]
